// Module included in the following assemblies:
//
// * service_mesh/v2x/installing-ossm.adoc


[id="ossm-remove-cleanup_{context}"]
= Clean up Operator resources

You can manually remove resources left behind after removing the {ProductName} Operator using the {product-title} web console.

.Prerequisites

* An account with cluster administration access. If you use {product-dedicated}, you must have an account with the `dedicated-admin` role.
* Access to the OpenShift CLI (`oc`).

.Procedure

. Log in to the {product-title} CLI as a cluster administrator.

. Run the following commands to clean up resources after uninstalling the Operators. If you intend to keep using Jaeger as a stand-alone service without service mesh, do not delete the Jaeger resources.
+
[NOTE]
====
The OpenShift Elasticsearch Operator is installed in `openshift-operators-redhat` by default. The other Operators are installed in the `openshift-operators` namespace by default. If you installed the Operators in another namespace, replace `openshift-operators` with the name of the project where the {ProductName} Operator was installed.
====
+
[source,bash]
----
$ oc delete validatingwebhookconfiguration/openshift-operators.servicemesh-resources.maistra.io
----
+
[source,bash]
----
$ oc delete mutatingwebhookconfigurations/openshift-operators.servicemesh-resources.maistra.io
----
+
[source,bash]
----
$ oc delete svc maistra-admission-controller -n openshift-operators
----
+
[source,bash]
----
$ oc delete -n openshift-operators daemonset/istio-node
----
+
[source,bash]
----
$ oc delete clusterrole/istio-admin clusterrole/istio-cni clusterrolebinding/istio-cni
----
+
[source,bash]
----
$ oc delete clusterrole istio-view istio-edit
----
+
[source,bash]
----
$ oc delete clusterrole jaegers.jaegertracing.io-v1-admin jaegers.jaegertracing.io-v1-crdview jaegers.jaegertracing.io-v1-edit jaegers.jaegertracing.io-v1-view
----
+
[source,bash]
----
$ oc get crds -o name | grep '.*\.istio\.io' | xargs -r -n 1 oc delete
----
+
[source,bash]
----
$ oc get crds -o name | grep '.*\.maistra\.io' | xargs -r -n 1 oc delete
----
+
[source,bash]
----
$ oc get crds -o name | grep '.*\.kiali\.io' | xargs -r -n 1 oc delete
----
+
[source,bash]
----
$ oc delete crds jaegers.jaegertracing.io
----
+
[source,bash]
----
$ oc delete secret -n openshift-operators maistra-operator-serving-cert
----
+
[source,bash]
----
$ oc delete cm -n openshift-operators maistra-operator-cabundle
----
