---
title: Deploying applications on Maistra
type: "document"
id: "deploying-applications-ossm"
weight: 11
---

[id="deploying-applications-ossm"]
= Enabling sidecar injection
include::modules/ossm-document-attributes.adoc[]
:context: deploying-applications-ossm

toc::[]

After adding your services to a mesh, enable automatic sidecar injection in the deployment resource for your application. You must enable automatic sidecar injection for each deployment. 

If you have installed the Bookinfo sample application, the application was deployed and the sidecars were injected. If you are using your own project and service, deploy your applications on {product-title}. For more information, see link:https://docs.openshift.com/container-platform/4.9/applications/deployments/what-deployments-are.html[Understanding Deployment and DeploymentConfig objects].

== Prerequisites

* xref:/docs/installing-ossm.adoc#installing-ossm[Adding services to a service mesh]
* A deployment resource for your project

include::modules/ossm-automatic-sidecar-injection.adoc[leveloffset=+1]

include::modules/ossm-update-app-sidecar.adoc[leveloffset=+1]

include::modules/ossm-sidecar-injection-env-var.adoc[leveloffset=+1]

== Next steps

Configure {ProductName} features for your environment.

* xref:/docs/ossm-security.adoc#ossm-security[Security]
* xref:/docs/ossm-traffic-manage.adoc#ossm-routing-traffic[Traffic management]
* xref:/docs/ossm-observability.adoc#ossm-observability[Metrics and traces]
