---
title: "Contributing"
---

== Reporting Issues

Please report issues to https://issues.jboss.org/projects/MAISTRA[Jira].

== Sources

Maistra's source code can be found in the locations below.

* link:https://github.com/maistra/maistra.github.io[Maistra.io]
* link:https://github.com/Maistra/istio[Maistra's Istio fork]
* link:https://github.com/Maistra/istio-operator[Operator]
* link:https://github.com/Maistra/proxy[Proxy]
* link:https://github.com/Maistra/istio-cni[Istio CNI]

== Upstream

* https://istio.io[Istio Website]
* https://github.com/istio/community/blob/master/WORKING-GROUPS.md[Istio Working Groups]
* https://github.com/istio[Istio Source]

== Documentation code review process

In order for documentation to be merged, the following are required: 

* Review from two members of the Maistra team
* Successful build
* No broken links
* No spelling errors
* Documentation must be written according to the link:https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#user-content-writing-concepts[OpenShift documentation style guide].

== Branching strategy

Every Maistra minor release has a branch of the format `maistra-release` in every repository. For example,
the 1.0 release has a branch `maistra-1.0` and 1.1 has a branch `maistra-1.1`. This is
true for all branches including documentation. On every release, a tag is created for the current patch, 
for example `maistra-1.1.0`.

On every minor release, a new Maistra subdomain is created for the release in development, and the
Maistra website is switched to point at the current active release branch. The default branch for all
repositories is changed to point at the newest development branch. This means that the branch that
the Maistra.io website is based off of or that code is deployed from is always one minor release behind. 
For example, when the default branch for Maistra.io is `maistra-1.2`, then the branch that is being
deployed to Maistra.io is `maistra-1.1`.
