---
title: "Installing a control plane"
type: "document"
category: "Getting started"
description: "These instructions will show you how to deploy a control plane."
weight: 2
---

== Creating a Maistra Control Plane
Maistra supports the deployment of multiple Istio control planes using `ServiceMeshMemberRoll`
and `ServiceMeshControlPlane` resources. The _ServiceMeshMemberRoll_ lists the projects belonging
to the control plane while the _ServiceMeshControlPlane_ lists the configuration to use during installation.
`ServiceMeshControlPlane` can be shortened to `smcp` and `ServiceMeshMemberRoll` can be shortened to `smmr`.

=== ServiceMeshControlPlane
To deploy the Istio Control Plane, create a `ServiceMeshControlPlane` such as the one in the following example.
The example uses `istio-system` as the control plane project. For more information about the parameters and their
configuration, see the link:../installation-options[installation options].

{{< snippet_markdown name="istio_installation_minimal" >}}

Once you have modified the `ServiceMeshControlPlane` to suit your installation you can deploy the resource using the following command,
substituting `istio-system`if appropriate.

```
$ oc new-project istio-system
$ oc create -n istio-system -f <name of file>
```

== Deploying a Maistra Control Plane using Catalog Web UI
:leveloffset: +1
OpenShift web console can be used to create control plane and member roll custom resources. Please reference link:https://docs.openshift.com/container-platform/4.1/applications/operators/olm-creating-apps-from-installed-operators.html[documentation on creating applications from installed operators] for more details.

To create a control plane, open the OpenShift web console in a Web browser and create a new project. This example uses a project called `istio-system`.

* Navigate to *Catalogs* -> *Installed Operators*.
* Click *Copied* and click the `Maistra` operator to view more actions.
* Under *Provided APIs*, you will see that the Operator creates two resource types:
- An Istio Service Mesh Control Plane
- An Istio Service Mesh Member Roll
* In the *Istio Service Mesh Control Plane* box:
- Click *Create New*. This screen allows you to modify the minimal template of a `ServiceMeshControlPlane` object, such as the cluster size.
- Click *Create* to finalize.
* Create a `ServiceMeshMemberRoll` by choosing the *Istio Service Mesh Member Roll* box and repeating these actions.

:leveloffset: -1

=== Verifying Installation
:leveloffset: +2

{{< snippet_markdown name="verify_install" >}}

:leveloffset: -2

[[remove_control_plane]]

=== Removing a Control Plane

{{% notice note %}}
Substitute the proper project below if the controlplane was created in a project other than `istio-system`.
{{% /notice %}}

The following steps will remove Istio from an existing installation. It can be
executed by any user in the `maistra-admin` `ClusterRoleBinding` for the control plane project.

To get the name of the installed `ServiceMeshControlPlane`, type:
```
$ oc get servicemeshcontrolplanes -n istio-system
```

This resource can now be deleted as follows:
```
$ oc delete smcp -n istio-system <name_of_cr>
$ oc delete project istio-system
```

The removal of the CustomResource will tell the Istio operator to begin uninstalling everything it installed.


=== Removing a Control Plane using Catalog Web UI

:leveloffset: +1

To remove a control plane, open the OpenShift web console in a Web browser and:

*  Navigate to *Catalog* -> *Installed Operators*.
* Choose the `istio-system` from the Project menu.
* Click the menu on the `ServiceMeshMemberRoll` row.
* Click *Details* -> *Delete Service Mesh Member Roll*.
* Click the menu on the `ServiceMeshControlPlane` row.
* Click *Details* -> *Delete Service Mesh Control Plane*.

:leveloffset: -1

== Upgrading a control plane

If you installed the Maistra operator using the `Automatic Approval Strategy`,
then the operator and control plane will update automatically. If not, then you
will have to manually upgrade each of the operators.  In either case, the
application sidecars must be updated separately from the control plane.

If your deployment is using automatic injection, then the application
only needs to be restarted to update the pod. Execute the following to
update the deployment and trigger an update for all pods that are part of the
deployment:

```
$ oc patch deployment/<deployment> -p '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt": "'`date -Iseconds`'"}}}}}'
```

If your deployment uses manual injection, you must manually update the sidecars
by modifying the sidecar container image specified in the deployment or pod.
