---
title: "Installing on OKD/OCP"
type: "document"
category: "Getting started"
description: "This document describes how to install the Istio operator and how to configure and install Maistra into your OpenShift installation."
weight: 1
---

:toc:

== Istio Installation Guide
This guide provides instructions for installing Maistra into an existing OpenShift Container Platform (OCP) or Origin (OKD) cluster and for creating a standalone, all-in-one origin cluster with Istio

=== Tested Configurations
- link:https://docs.openshift.com/container-platform/3.11/install/prerequisites.html[OpenShift Container Platform (OCP) 3.11]/Origin (OKD) 3.11. The link:../add-redhat-registry[Red Hat registry] and link:../311-nodes[nodes] must be configured before installing.
- OpenShift Container Platform (OCP) 4.1
- NOTE: We no longer maintain a version of `oc cluster up` for use with Service Mesh and we do not yet run within an OpenShift Online or OpenShift Dedicated environment.

== Installing Maistra
Maistra requires the ElasticSearch, Jaeger, and Kiali operators to be installed before Maistra operator itself can be installed. Please reference link:https://docs.openshift.com/container-platform/4.1/applications/operators/olm-adding-operators-to-cluster.html[documentation on adding operators to a cluster] for detailed instructions on how to install operators using OLM.

=== Installing the Maistra Operator
:leveloffset: +1

Open the OpenShift web console in a Web browser and navigate to *Catalog* -> *OperatorHub*. Select the community Maistra Operator to display information about the Operator. Click *Install*. On the *Create Operator Subscription* page, select *All namespaces on the cluster (default)*. This installs the Operator in the default `openshift-operators` project and is made available to all projects in the cluster. Select either *Automatic* or *Manual* approval strategy. Click *Subscribe*.

:leveloffset: -1

== Verifying Installation
The above instructions will create a new deployment within the istio-operator project, executing the operator responsible for managing the state of the Istio control plane through the *ServiceMeshControlPlane*.

To verify the operator is installed correctly, wait for the operator to reach the running state

```
oc get pods -n istio-operator -l name=istio-operator

NAME                              READY     STATUS    RESTARTS   AGE
istio-operator-5cd6bcf645-fvb57   1/1       Running   0          1h
```

== Deploying the Istio Control Plane
Maistra supports the deployment of multiple Istio control planes using *ServiceMeshMemberRoll*
and *ServiceMeshControlPlane* resources. The *ServiceMeshMemberRoll* lists the projects belonging
to the control plane while the *ServiceMeshControlPlane* lists the configuration to use during installation.
*ServiceMeshControlPlane* can be shortened to `smcp` and *ServiceMeshMemberRoll* can be shortened to `smmr`.

=== ServiceMeshMemberRoll
The *ServiceMeshMemberRoll* resource configures which projects belong to a control plane.
Only projects listed in the *ServiceMeshMemberRoll* will be affected by the control plane.
Any number of projects can be added, but a project may not exist in more than one control plane.
This resource must be created in the same project as the *ServicemeshControlPlane* resource
and must be named default. An example resource can be seen below:

{{% notice note %}}
The control plane processes the *ServiceMeshMemberRoll* when: the *ServiceMeshMemberRoll* is created, updated, or deleted,
the *ServicemeshControlPlane* in the same project is created or updated, or a project in the *ServiceMeshMemberRoll* is created or deleted.
{{% /notice %}}


{{< snippet_markdown name="istio_installation_smmr" >}}

=== ServiceMeshControlPlane
In order to deploy the Istio Control Plane, create a *ServiceMeshControlPlane* such as the one in the following example.
The example below uses `istio-system` as the control plane project. For more information on the parameters and their
configuration please see the link:../custom-install[custom installation documentation].

{{< snippet_markdown name="istio_installation_minimal" >}}

Once you have modified the *ServiceMeshControlPlane* to suit your installation you can deploy the resource using the following command,
substituting istio-system if appropriate.

```
oc new-project istio-system
oc create -n istio-system -f <name of file>
```

== Deploying the Istio Control Plane using Catalog Web UI
:leveloffset: +1
Openshift web console can be used to create control plane and member roll custom resources. Please reference link:https://docs.openshift.com/container-platform/4.1/applications/operators/olm-creating-apps-from-installed-operators.html[documentation on creating applications from installed operators] for more details.

Open the OpenShift web console in a Web browser. Create a new project. This example uses a project called `istio-system`. Navigate to *Catalogs* -> *Installed Operators*. Click *Copied* and click the Maistra Operator to view more actions. Under *Provided APIs* you will see that the Operator creates two resource types:
* An Istio Service Mesh Control Plane
* An Istio Service Mesh Member Roll

In the *Istio Service Mesh Control Plane* box click *Create New*. This screen allows you to modify the minimal template of a `ServiceMeshControlPlane` object, such as the cluster size. Click *Create* to finalize. Create a `ServiceMeshMemberRoll` by choosing the *Istio Service Mesh Member Roll* box and repeating these actions. 

:leveloffset: -1

=== Verifying Installation
:leveloffset: +2

{{< snippet_markdown name="verify_install" >}}

:leveloffset: -2

== Control Plane Templates
Templates follow the same syntax as a *ServiceMeshControlPlane* and allow users to inherit settings in a hierarchical fashion. The operator
comes with a built-in `default` template containing the default settings for OpenShift Service Mesh or Maistra depending on the operator.
To add custom templates, create a ConfigMap called `smcp-templates` in the `openshift-operators` project. This ConfigMap will contain a collection
of templates to use. This ConfigMap must then be mounted in the operator at `/usr/local/share/istio-operator/templates/`.

=== Creating the ConfigMap
To create the ConfigMap, execute the following as a cluster administrator, substituting _templates-directory_ for a directory containing a
collection of *ServiceMeshControlPlane* files to use as templates. The name of the template will match the name of the file. Templates will
inherit from other templates until a template is reached which has an empty template field. Using a name of _default_ will override the
default template when no template is specified in a controlplane.


For example, create a ServiceMeshControlPlane and instead of using `oc apply` to create it in the cluster, save it in a
directory called _templates-directory_. Follow the instructions below to create and configure a ConfigMap using this new
template. Additional templates can be created the same way.

```
 oc create configmap --from-file=templates-directory smcp-templates -n openshift-operators
```
Next, find and edit the operator deloyment in the operator cluster service version to
instruct the operator to use the smcp-templates ConfigMap.

```
oc get clusterserviceversion -n openshift-operators | grep 'Service Mesh'
maistra.v1.0.0            Red Hat OpenShift Service Mesh   1.0.0                Succeeded

oc edit clusterserviceversion -n openshift-operators maistra.v1.0.0
```

In the editor, add a volume mount and volume as shown below.

```
 deployments:
        - name: istio-operator
          spec:
          ...
                    volumeMounts:
                      - mountPath: /home/istio-operator/.kube/cache/discovery
                        name: discovery-cache
                      - name: smcp-templates
                        mountPath: /usr/local/share/istio-operator/templates/
          ...
                volumes:
                  - emptyDir:
                      medium: Memory
                    name: discovery-cache
                  - name: smcp-templates
                    configMap:
                      name: smcp-templates
```

Templates can now be referenced by adding a *template* parameter to the *ServiceMeshControlPlane*.
```
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: minimal-install
spec:
  template: default
```

== Uninstalling Maistra

[[remove_control_plane]]

=== Removing the Control Plane

{{% notice note %}}
Subsitute the proper project below if the controlplane was created in a project other than istio-system.
{{% /notice %}}

The following steps will remove Istio from an existing installation. It can be executed by any user with access to delete the CustomResource.

To get the name of the installed *ServiceMeshControlPlane*, type:
```
oc get servicemeshcontrolplanes -n istio-system
```

This resource can now be deleted as follows:
```
oc delete smcp -n istio-system <name_of_cr>
oc delete project istio-system
```

The removal of the CustomResource will tell the Istio operator to begin uninstalling everything it installed.

=== Removing the Control Plane using Catalog Web UI

:leveloffset: +1

Open the OpenShift web console in a Web browser and navigate to *Catalog* -> *Installed Operators*. Choose the `istio-system` from the Project menu. Click the menu on the `ServiceMeshMemberRoll` row. Click *Details* -> *Delete Service Mesh Member Roll*. Click the menu on the `ServiceMeshControlPlane` row. Click *Details* -> *Delete Service Mesh Control Plane*.

:leveloffset: -1


[[remove_operator]]

=== Removing the Operator

=== Removing the Maistra Operator

:leveloffset: +1

Open the OpenShift web console in a Web browser and navigate to *Catalog* -> *Operator Management*. Select the *openshift-operators* project from the Projects drop-down. Locate the *Maistra* Operator and click *View Subscription*. Click the *More Operations* menu and select *Remove Subscription*. 

:leveloffset: -1

=== Removing the Kiali Operator

:leveloffset: +1

Open the OpenShift web console in a Web browser and navigate to *Catalog* -> *Operator Management*. Select the *openshift-operators* project from the Projects drop-down. Locate the *Kiali* Operator and click *View Subscription*. Click the *More Operations* menu and select *Remove Subscription*.      

:leveloffset: -1

=== Removing the Jaeger Operator

:leveloffset: +1

Open the OpenShift web console in a Web browser and navigate to *Catalog* -> *Operator Management*. Select the *openshift-operators* project from the Projects drop-down. Locate the *Jaeger* Operator and click *View Subscription*. Click the *More Operations* menu and select *Remove Subscription*.      

:leveloffset: -1

=== Removing the Elasticsearch Operator

:leveloffset: +1

Open the OpenShift web console in a Web browser and navigate to *Catalog* -> *Operator Management*. Select the *openshift-operators* project from the Projects drop-down. Locate the *Elasticsearch* Operator and click *View Subscription*. Click the *More Operations* menu and select *Remove Subscription*.      

:leveloffset: -1

== Upgrading from a Pre-Existing Installation

To upgrade Istio, please <<remove_control_plane, remove *ServiceMeshControlPlane*>>  and then create a one. The operator will upgrade appropriately.

To upgrade the operator, please first <<remove_operator, remove the operator>> and then reinstall it. Note that Istio must be removed before the operator.

{{% notice note %}}
If the operator was removed before the *ServiceMeshControlPlane*, you can uninstall the control plane manually. Using the instructions below
{{% /notice %}}

```
oc delete csr istio-sidecar-injector.istio-system
oc get crd  | grep istio | awk '{print $1}' | xargs oc delete crd
oc get mutatingwebhookconfigurations  | grep istio | awk '{print $1}' | xargs oc delete mutatingwebhookconfigurations
oc get validatingwebhookconfiguration  | grep istio | awk '{print $1}' | xargs oc delete validatingwebhookconfiguration
oc get clusterroles  | grep istio | awk '{print $1}' | xargs oc delete clusterroles
oc get clusterrolebindings  | grep istio | awk '{print $1}' | xargs oc delete clusterrolebindings
```
