---
title: "Releases"
type: "document"
category: "Getting started"
description: "This lists the Maistra releases."
weight: 0
---

== Security Issues

{{% notice warning %}}
Occasionally, security issues are found in Maistra. When issues are discovered, a new release
of OpenShift Service Mesh is made to include fixes for these vulnerabilities. However,
these fixes are not included in a Maistra release until the next general release.
{{% /notice %}}

The following table lists the versions of components in different releases.

{{< release-notes-table >}}

[[maistra-1.1.1]]
== Maistra 1.1.1
* Added support for disconnected installs. This feature is only available on OpenShift Service Mesh.


[[maistra-1.1.1]]
== Maistra 1.1.1
* Added support for disconnected installs. This feature is only available on OpenShift Service Mesh.

[[maistra-1.1.0]]
== Maistra 1.1.0
* Updated to Istio 1.4.6
* Support for Kiali `tag` field has been removed
* Operator dependencies removed. Kiali, Jaeger, and ElasticSearch must be installed independently.

