---
title: "Releases"
type: "document"
category: "Getting started"
description: "This lists the Maistra releases."
weight: 0
---

== Security Issues

{{% notice warning %}}
Occasionally, security issues are found in Maistra. When issues are discovered, a new release
of OpenShift Service Mesh is made to include fixes for these vulnerabilities. However,
these fixes are not included in a Maistra release until the next general release.
{{% /notice %}}

The following table lists the versions of components in different releases.

{{< release-notes-table >}}


[[maistra-1.1.3]]
== Maistra 1.1.3
* Removed cert-manager CRDs (Custom Resource Definitions) from control plane installation.  These were being installed
  by mistake.  These CRDs need to be removed manually if cert-manager is not being used within the Kubernetes cluster.
  To remove the CRDs, run the following commands:

[source,bash]
----
$ kubectl delete crd clusterissuers.certmanager.k8s.io
$ kubectl delete crd issuers.certmanager.k8s.io
$ kubectl delete crd certificates.certmanager.k8s.io
$ kubectl delete crd orders.certmanager.k8s.io
$ kubectl delete crd challenges.certmanager.k8s.io
----

[[maistra-1.1.1]]
== Maistra 1.1.1
* Added support for disconnected installs. This feature is only available on OpenShift Service Mesh.

[[maistra-1.1.0]]
== Maistra 1.1.0
* Updated to Istio 1.4.6
* Support for Kiali `tag` field has been removed
* Operator dependencies removed. Kiali, Jaeger, and ElasticSearch must be installed independently.

