+++
title = "Comparison with Istio"
chapter = false
weight = 2
+++


== Comparing Maistra and Istio installations

An installation of Maistra differs from an installation of Istio in multiple
ways. The modifications to Maistra are sometimes necessary to resolve issues,
provide additional features, or to handle differences when deploying on
OpenShift or OKD.

=== Automatic Injection

Enabling automatic injection for your deployments differs between the upstream
Istio releases and the Maistra releases.  The upstream sidecar injector will
inject all deployments within specifically labeled namespaces whereas the
Maistra version relies on presence of the 
`sidecar.istio.io/inject` annotation and the project being listed in the
`ServiceMeshMemberRoll`.  For more information please refer to the
link:{{< relref "automatic-injection.adoc" >}}[the automatic injection section].

=== Istio CNI

The _CNI plugin_ replaces proxy-init on OpenShift 4 clusters. Using CNI eliminates
the need for the `NET_ADMIN` privilege on application containers.

=== Istio Operator

Maistra uses a multi-tenant operator to manage the control plane lifecycle.
Whereas upstream Istio takes a single tenant approach, Maistra supports
multiple independent control planes within the cluster. This is discussed in
more detail during link:../installation/[installation]

=== Cluster Scoped Resources

Upstream Istio has two cluster scoped resources that it relies on. The MeshPolicy and the ClusterRbacConfig. These are not compatible with a multitenant cluster and have been replaced as described below.

* _ServiceMeshPolicy_ replaces MeshPolicy for configuration of control-plane-wide authentication policies. This must be created in the same namespace as the control plane.
* _ServicemeshRbacConfig_ replaces ClusterRbacConfig for configuration of control-plane-wide role based access control. This must be created in the same namespace as the control plane.

=== Component Modifications

* Godebug has been removed from all templates
* A _maistra-version_ label has been added to all resources.
* The istio-multi ServiceAccount and ClusterRoleBinding have been removed, as well as the istio-reader ClusterRole.
* All Ingress resources have been converted to OpenShift Route resources.
* Grafana, Tracing (Jaeger), and Kiali are enabled by default and exposed via OpenShift routes.
