---
title: "Custom Installation"
type: "document"
category: "Getting started"
description: "Maistra uses a custom resource to initialize your environment. This document describes how to customize the installation to your specific environment."
weight: 2
hidden: true
---

== Example Configuration
Maistra uses the istio-operator, a custom install built around Istio's helm charts. Many of the parameters supported by the installer are shown below. For further options, see the link: https://istio.io/docs/reference/config/installation-options/[helm docs].

{{< snippet_markdown name="istio_installation_auth" >}}

== Customizing the Installation
If you wish to customize your installation further, an explanation of different parameters is below. 

## [[istio_globals]] Istio Globals

[source,yaml]
----
  istio:
    global:
      hub: my-private-registry.com/custom-namespace
      tag: 0.10.0 
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      disablePolicyChecks: true
      policyCheckFailOpen: false
      imagePullSecrets:
        - MyPullSecret


----

### proxy 

#### resources->requests
These are the resources requested and may vary depending on your environment. The example above allows Maistra to run in a smaller environment. 

* cpu 
** Description: This is the number of CPUs that are requested in the environment.  
** Default: 100m

* memory
** Description: This is the ammount of memory that is requested in the environment. 
** Default: 128Mi

#### resources -> limits
These are the resources requested and may vary depending on your environment. The example above allows Maistra to run in a smaller environment. 

* cpu
** Description: This is the maximum number of CPUs that proxy is allowed to use.
** Default: 2000m

* memory 
** Description: This is the maximum ammount of memory that proxy is allowed to use. 
** Default: 128Mi

* imagePullSecret 
** Description: If access to the registry providing the Istio images is secure, then an link:https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod[imagePullSecret] can be listed here.
** Default: none

### disablePolicyChecks
{{% notice info %}}
This must be false for 3 Scale to work.
{{% /notice %}}
* Description: This is a boolean indicating whether to enable policy checks. As of Maistra 0.9.
* Default: true

### policyCheckFailOpen
* Description: This is a boolean indicating wehther to traffic should be allowed through hwen the mixer policy service cannot be reached. The default value is false.
* Default: false

### mtls

* enabled
** Description: this parameter controls whether to enable mTLS between services by default. 
** Default: false

### hub

** Description: The hub to use to pull the Istio images. 
** Default: maistra/ if deployment_type is origin and openshift-istio-tech-preview/ if deployment_type is openshift

### tag

** Description: The tag to use to pull the Istio images. 
** Default: 0.10.0

## [[Gateways]] istio->gateways

[source,yaml]
----
 gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        autoscaleMin: 1
        autoscaleMax: 5
      istio-ingressgateway:
        autoscaleEnabled: false
        autoscaleMin: 1
        autoscaleMax: 5
        ior_enabled: false

----

### istio-egressgateway

* autoscaleEnabled
** Description: This parameter controls whether autoscaling is enabled. The example above disables it to allow running Maistra in a smaller environment. 
** Default: true

### istio-ingressgateway

* autoscaleEnabled
** Description: This parameter controls whether autoscaling is enabled. The example above disables it to allow running Maistra in a smaller environment. 
** Default: true

* autoscaleMin
** Description: This parameter controls the minimum pods to deploy based on the autoscaleEnabled setting.
** Default: 1

* autoscaleMax
** Description: This parameter controls the minimum pods to deploy based on the autoscaleEnabled setting.
** Default: 5

* ior_enabled
** Description: This parameter controls whether Istio routes should automatically be configured in OpenShift
** Default: false
    
## [[Mixer]] istio->mixer

[source,yaml]
----
 mixer:
      policy:
        autoscaleEnabled: false

      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G
----

* enabled
** Description: This parameter controls whether to enable Mixer.
** Default: true

* autoscaleEnabled
** Description: This parameter controls whether to enable autoscaling. Disable this for smaller environments.
** Default: true

* autoscaleMin
** Description: This parameter controls the minimum pods to deploy based on the autoscaleEnabled setting.
** Default: 1

* autoscaleMax
** Description: This parameter controls the minimum pods to deploy based on the autoscaleEnabled setting.
** Default: 5

### telemetry
#### resources->requests
These are the resources requested and may vary depending on your environment. The example above allows Maistra to run in a smaller environment. 

* cpu 
** Description: This is the number of CPUs that are requested in the environment.  
** Default: 1000m

* memory
** Description: This is the ammount of memory that is requested in the environment. 
** Default: 1G

#### resources -> limits
These are the resources requested and may vary depending on your environment. The example above allows Maistra to run in a smaller environment. 

* cpu
** Description: This is the maximum number of CPUs that telemetry is allowed to use.
** Default: 4800m

* memory 
** Description: This is the maximum ammount of memory that telemetry is allowed to use. 
** Default: 4G

## [[Pilot]] istio->pilot

[source,yaml]
----
   pilot:
      autoscaleEnabled: false
      traceSampling: 100.0
----

### resources->requests
These are the resources requested and may vary depending on your environment. 

* cpu 
** Description: This is the number of CPUs that are requested in the environment.  
** Default: 500m

* memory
** Description: This is the ammount of memory that is requested in the environment. 
** Default: 2048Mi

* traceSampling
** Description: This value controls how often random sampling should occur. Increase for development/testing.
** Default: 1.0

## [[Kiali]] istio->kiali

[source,yaml]
----
   kiali:
      enabled: true
      hub: kiali
      tag: v0.16.2
      #dashboard:
        #user: admin
        #passphrase: admin
----

### enabled 

** Description: This enables or disables Kiali in the environment.  
** Default: true


### hub

** Description: The hub to use to pull the Kiali images. 
** Default: kiali/ if deployment_type is origin and openshift-istio-tech-preview/ if deployment_type is openshift

### tag

** Description: The tag to use to pull the Istio images. 
** Default: 0.16.2


### dashboard
{{% notice info %}}
Kiali supports two authentication modes. OAuth and dashboard users. By default, Kiali uses OpenShift OAuth, but you can enable a dashboard user by adding a dashboard user and passphrase.
{{% /notice %}}

* user
** Description: This is the username used to access the Kiali console. Note that this is not related to any account on OpenShift
** Default: none

* passphrase
** Description: This is the password used to access the Kiali console. Note that this is not related to any account on OpenShift.
** Default: none 

## [[Tracing]] istio->tracing
* enabled
** Description: This enables or disables tracing in the environment.  
** Default: true


## 3scale
{{% notice info %}}
disablePolicyChecks must be false for 3 Scale to work.
{{% /notice %}}

[source,yaml]
----
    threescale:
        enabled: true
        PARAM_THREESCALE_LISTEN_ADDR: 3333
        PARAM_THREESCALE_LOG_JSON: true
        PARAM_THREESCALE_LOG_JSON: true
        PARAM_THREESCALE_REPORT_METRICS: true
        PARAM_THREESCALE_METRICS_PORT: 8080
        PARAM_THREESCALE_CACHE_TTL_SECONDS: 300
        PARAM_THREESCALE_CACHE_REFRESH_SECONDS: 180
        PARAM_THREESCALE_CACHE_ENTRIES_MAX: 1000
        PARAM_THREESCALE_CACHE_REFRESH_RETRIES: 1
        PARAM_THREESCALE_ALLOW_INSECURE_CONN: false
        PARAM_THREESCALE_CLIENT_TIMEOUT_SECONDS: 10
----

* enabled
** Description: This controls whether to enable 3scale.
** Default: false

* PARAM_THREESCALE_LISTEN_ADDR
** Description: This sets the listen address for the gRPC server.
** Default: 3333

* PARAM_THREESCALE_LOG_LEVEL
** Description: This sets  the minimum log output level. Accepted values are one of debug,info,warn,error,none
** Default: info

* PARAM_THREESCALE_LOG_JSON
** Description: This controls whether the log is formatted as JSON
** Default: true

* PARAM_THREESCALE_REPORT_METRICS
** Description: This controls whether the 3scale system and backend metrics are collected and reported to Prometheus
** Default: true

* PARAM_THREESCALE_METRICS_PORT
** Description: This sets the port which 3scale /metrics endpoint can be scrapped from
** Default: 8080

* PARAM_THREESCALE_CACHE_TTL_SECONDS
** Description: This is the time period, in seconds, to wait before purging expired items from the cache
** Default: 300

* PARAM_THREESCALE_CACHE_REFRESH_SECONDS
** Description: This is the time period before expiry, when cache elements are attempted to be refreshed
** Default: 180

* PARAM_THREESCALE_CACHE_ENTRIES_MAX
** Description: This is the ax number of items that can be stored in the cache at any time. Set to 0 to disable caching.
** Default: 1000

* PARAM_THREESCALE_CACHE_REFRESH_RETRIES
** Description: This sets the number of times unreachable hosts will be retried during a cache update loop.
** Default: 1

* PARAM_THREESCALE_ALLOW_INSECURE_CONN
** Description: This controls whether to allow certificate verification when calling 3scale API’s. Enabling is not recommended
** Default: false

* PARAM_THREESCALE_CLIENT_TIMEOUT_SECONDS
** Description: This sets the number of seconds to wait before terminating requests to 3scale System and Backend
** Default: 10

## Launcher

[source,yaml]
----
    threescale:
        enabled: true
        LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME: username
        LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN: token
        LAUNCHER_MISSIONCONTROL_OPENSHIFT_API_URL: https://kubernetes.default.svc.cluster.local
        LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL: ''
        LAUNCHER_KEYCLOAK_URL: ''
        LAUNCHER_KEYCLOAK_REALM: ''
        LAUNCHER_TRACKER_SEGMENT_TOKEN: token
        LAUNCHER_BOOSTER_CATALOG_REPOSITORY: https://github.com/fabric8-launcher/launcher-booster-catalog.git
        LAUNCHER_BOOSTER_CATALOG_REF: v85
        LAUNCHER_BACKEND_CATALOG_FILTER: booster.mission.metadata.istio
        LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN: token
        LAUNCHER_BACKEND_ENVIRONMENT: environment

----


* enabled
** Description: This controls whether to enable launcher.
** Default: false

* LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME
** Description: The GitHub user to use in Fabric8.
** Default: none

* LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN
** Description: The GitHub token to use in Fabric8.
** Default: none

* LAUNCHER_MISSIONCONTROL_OPENSHIFT_API_URL
** Description: The base URL of the OpenShift API where the launched boosters should be created (ie. https://hostname[:port] or https://ipaddress[:port]).
** Default: https://kubernetes.default.svc.cluster.local. This does not need to be set when targing the same OpenShift instance that you are running this on.

* LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL
** Description: The base URL of the OpenShift Console where the launched boosters should be created (ie. https://hostname[:port] or https://ipaddress[:port]).
** Default: Empty. This does not need to be set when targing the same OpenShift instance that you are running this on.

* LAUNCHER_KEYCLOAK_URL
** Description: The URL (with the /auth part) of a Keycloak installation to perform SSO authentication.
** Default: Empty. Leave empty if you've explicitly specified GitHub/OpenShift authentication.

* LAUNCHER_KEYCLOAK_REALM
** Description: The keycloak realm to be used.
** Default: Empty. Leave empty if you've explicitly specified GitHub/OpenShift authentication


* LAUNCHER_TRACKER_SEGMENT_TOKEN
** Description: The token to use for Segment tracking.
** Default: None
{{% notice info %}}
Leaving this empty will disable tracking. This must be set to the proper tokens for staging and production!
{{% /notice %}}

* LAUNCHER_BOOSTER_CATALOG_REPOSITORY
** Description: The GitHub repository containing the booster catalog
** Default: https://github.com/fabric8-launcher/launcher-booster-catalog.git

* LAUNCHER_BOOSTER_CATALOG_REF
** Description: The GitHub branch containing the booster catalog
** Default: v85

* LAUNCHER_BACKEND_CATALOG_FILTER
** Description: The Red Hat booster catalog filter.
** Default: booster.mission.metadata.istio

* LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN
** Description: The Red Hat booster catalog filter.
** Default:Empty

* LAUNCHER_BACKEND_ENVIRONMENT
** Description:  The environment where this backend is running.
** Default: Empty. Leaving this empty will set the value to 'development' if the 'Catalog Git Reference' is set to 'master', in any other case the value will default to 'production'.
