---
title: "Installing on OKD/OCP"
type: "document"
category: "Getting started"
description: "This document describes how to install the Istio operator and how to configure and install Maistra into your OpenShift installation."
weight: 1
---

:toc:

== Istio Installation Guide

This guide provides instructions for installing Maistra into an existing OpenShift Container Platform (OCP) or Origin (OKD) cluster and for creating a standalone, all-in-one origin cluster with Istio

=== Tested Configurations

- link:https://docs.openshift.com/container-platform/3.11/install/prerequisites.html[OpenShift Container Platform (OCP) 3.11]/Origin (OKD) 3.11. The link:../add-redhat-registry[Red Hat registry] and link:../311-nodes[nodes] must be configured before installing.
- OpenShift Container Platform (OCP) 4.1
- NOTE: We no longer maintain a version of `oc cluster up` for use with Service Mesh and we do not yet run within an OpenShift Online or OpenShift Dedicated environment.



== Installing Maistra
=== Installing the Kiali Operator

:leveloffset: +1

{{< snippet_markdown name="install_kiali" >}}

:leveloffset: -1

=== Installing the Elasticsearch operator

:leveloffset: +1

{{< snippet_markdown name="install_elasticsearch" >}}

:leveloffset: -1

=== Installing the Jaeger operator

:leveloffset: +1

{{< snippet_markdown name="install_jaeger" >}}

:leveloffset: -1

=== Installing the Istio Operator

The Maistra installation process introduces a Kubernetes operator to manage the installation, update, and removal of the Istio control plane within the istio-system project.

The templates are available at: https://github.com/Maistra/istio-operator/tree/maistra-1.0/deploy/examples

The following steps will install the Maistra operator into an existing installation, these can be executed from any host with access to the cluster.  Please ensure you are logged in as a cluster admin before executing the following

```
oc new-project istio-operator
oc apply -n istio-operator -f https://raw.githubusercontent.com/Maistra/istio-operator/maistra-1.0/deploy/maistra-operator.yaml
```

== Verifying Installation

The above instructions will create a new deployment within the istio-operator project, executing the operator responsible for managing the state of the Istio control plane through the *ServiceMeshControlPlane*.

To verify the operator is installed correctly, wait for the operator to reach the running state

```
oc get pods -n istio-operator -l name=istio-operator

NAME                              READY     STATUS    RESTARTS   AGE
istio-operator-5cd6bcf645-fvb57   1/1       Running   0          1h
```

== Deploying the Istio Control Plane
Maistra supports the deployment of multiple Istio control planes using *ServiceMeshMemberRoll*
and *ServiceMeshControlPlane* resources. The *ServiceMeshMemberRoll* lists the projects belonging
to the control plane while the *ServiceMeshControlPlane* lists the configuration to use during installation.
*ServiceMeshControlPlane* can be shortened to `smcp` and *ServiceMeshMemberRoll* can be shortened to `smmr`.

=== ServiceMeshMemberRoll
The *ServiceMeshMemberRoll* resource configures which projects belong to a control plane.
Only projects listed in the *ServiceMeshMemberRoll* will be affected by the control plane.
Any number of projects can be added, but a project may not exist in more than one control plane.
This resource must be created in the same project as the *ServicemeshControlPlane* resource
and must be named default. An example resource can be seen below:

{{% notice note %}}
The control plane processes the *ServiceMeshMemberRoll* when: the *ServiceMeshMemberRoll* is created, updated, or deleted,
the *ServicemeshControlPlane* in the same project is created or updated, or a project in the *ServiceMeshMemberRoll* is created or deleted.
{{% /notice %}}


{{< snippet_markdown name="istio_installation_smmr" >}}

=== ServiceMeshControlPlane
In order to deploy the Istio Control Plane, create a *ServiceMeshControlPlane* such as the one in the following example.
The example below uses `istio-system` as the control plane project. For more information on the parameters and their
configuration please see the link:../custom-install[custom installation documentation].

{{< snippet_markdown name="istio_installation_minimal" >}}

Once you have modified the *ServiceMeshControlPlane* to suit your installation you can deploy the resource using the following command,
substituting istio-system if appropriate.

```
oc new-project istio-system
oc create -n istio-system -f <name of file>
```

=== Verifying Installation
:leveloffset: +2

{{< snippet_markdown name="verify_install" >}}

:leveloffset: -2

== Uninstalling Maistra

[[remove_control_plane]]

=== Removing the Control Plane

{{% notice note %}}
Subsitute the proper project below if the controlplane was created in a project other than istio-system.
{{% /notice %}}

The following steps will remove Istio from an existing installation. It can be executed by any user with access to delete the CustomResource.

To get the name of the installed *ServiceMeshControlPlane*, type:
```
oc get servicemeshcontrolplanes -n istio-system
```

This resource can now be deleted as follows:
```
oc delete smcp -n istio-system <name_of_cr>
oc delete project istio-system
```

The removal of the CustomResource will tell the Istio operator to begin uninstalling everything it installed.

[[remove_operator]]

=== Removing the Operator

=== Removing the Kiali Operator

:leveloffset: +1

{{< snippet_markdown name="remove_kiali" >}}

:leveloffset: -1

=== Removing the Jaeger operator

:leveloffset: +1

{{< snippet_markdown name="remove_jaeger" >}}

:leveloffset: -1

=== Removing the Elasticsearch operator

:leveloffset: +1

{{< snippet_markdown name="remove_elasticsearch" >}}

:leveloffset: -1

==== Removing the Maistra Operator
In order to cleanly remove the operator execute the following:

```
oc delete -n istio-operator -f https://raw.githubusercontent.com/Maistra/istio-operator/maistra-1.0/deploy/maistra-operator.yaml
oc delete validatingwebhookconfiguration/istio-operator.servicemesh-resources.maistra.io
```

The *istio-operator* project can now be removed.

```
oc delete project istio-operator
```

== Upgrading from a Pre-Existing Installation

If you installed the Maistra operator using the `Automatic Approval Strategy`,
then the operator and control plane will update automatically. If not, then you
will have to manually upgrade each of the operators.  In either case, the
application sidecars must be updated separately from the control plane. 

If your deployment is using using automatic injection, then the application
only needs to be restarted in order to update the pod. Execute the following to
update the deployment and trigger an update for all pods that are part of the
deployment: 

```
$ oc patch deployment/<deployment> -p '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt": "'`date -Iseconds`'"}}}}}'
```

If your deployment uses manual injection, you must manually update the sidecars
by modifying the sidecar container image specified in the deployment or pod.
