---
title: "Enabling Mesh-wide RBAC Policy Enforcement"
type: "document"
category: "Examples"
description: "Configure Maistra to enforce RBAC rules for all communication inside the service mesh."
---

{{% notice info %}}
Using RBAC policies requires mTLS strict mode. For information on how to enable it, see link:../mesh-wide_mtls/[Enabling Mesh-wide Strict mTLS].
{{% /notice %}}

== Introduction

Istio supports policies that define Role-based Access Control rules (RBAC) to specify which services can communicate within the mesh. Role-based means that you first create a role that defines a set of actions that can legally be performed on a set of resources, and then map the defined role to a set of services. The ServiceRole can define e.g. legal HTTP verbs and endpoints for HTTP services, or access to certain ports for TCP services. The resources resemble the https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Kubernetes RBAC objects]. If you are familiar with those, you should be able to get started quickly with using Maistra's RBAC functionality.

The following example will enable RBAC policy enforcement in your Maistra mesh. Note that without any further action, this will make communication between your services impossible, because by default, _Istio's RBAC functionality will deny all requests that are not explicitly permitted_.

=== Creating the ServiceMeshRbacConfig

Creating the following resource in your control plane's namespace will enable RBAC policy enforcement in your mesh:

[source,yaml]
----
apiVersion: "maistra/v1"
kind: ServiceMeshRbacConfig
metadata:
  name: default
  namespace: <CONTROL_PLANE_NS>
spec:
  mode: 'ON'
----

{{% notice tip %}}
This resource does not exist in upstream Istio, it has been added to Maistra. It replaces the upstream ClusterRbacConfig, which is cluster-scoped. For more information, see the link:../../comparison-with-istio/#cluster_scoped_resources[comparison of Maistra and upstream Istio].
{{% /notice %}}

=== See also

- https://istio.io/docs/tasks/security/authz-http/[Istio Task: Authorization for HTTP Services]
- https://istio.io/docs/tasks/security/authz-tcp/[Istio Task: Authorization for TCP Services]
- https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Kubernetes Docs: Using RBAC Authorization]